#!/bin/bash

set -e
source ./common.sh

############################################################

explain "Checking prerequisites.."

check_command minicom
check_command 7z
check_command udisks
check_command curl
check_command bspatch

finish "Prerequisites found. Proceed to next step."
