#!/bin/bash

set -e
source ./common.sh

############################################################

explain "Detecting and mounting Micro-SD card..."
SD_MOUNTPOINT=$(prs_mount_sd) || abort "Mounting of SD card failed. Ensure reader is connected and not in recovery mode."

explain "Copying rescue files..."
rm -vrf "$SD_MOUNTPOINT/OS Firmware"
cp -vr "packages/rupor-rescue/OS Firmware" $SD_MOUNTPOINT

explain "Unmounting Micro-SD card..."
prs_unmount_sd

finish "Rescue files copied. Please restart reader in recovery mode."

