#!/bin/bash

set -e
source ./common.sh

############################################################

explain "Detecting and mounting SD card..."
SD_MOUNTPOINT=$(prs_mount_sd) || abort "Mounting of SD card failed. Ensure device is connected and not in recovery mode."

explain "Copying jailbreak files..."
rm -vrf "$SD_MOUNTPOINT/OS Firmware"
cp -vr "packages/rupor-jailbreak/OS Firmware" $SD_MOUNTPOINT

explain "Unmounting SD card..."
prs_unmount_sd
r
finish "Jailbreak files copied. Please restart device in recovery mode."
